### ISSUE TITLE
请问能分享一下原始数据集么？万分感谢！

### ISSUE THREAD

**Issue by Explorerli** [seattleboy/2017_JDD_sale#2]

**Comment by seattleboy** [comment]
我找下哈

**Comment by haitwang-cloud** [comment]
https://jdder.jd.com/index/jddDetail?matchId=0890e7edc3c840ea9351e9d736da1e16
可以在这个链接里面找到

**Comment by haitwang-cloud** [comment]
https://cloud.tencent.com/developer/article/1005559【实习生的监控算法: 利用时间序列模型进行曲线预测】这个链接是我看到的比较好的时间序列算法介绍，感兴趣的可以看下

**Comment by Explorerli** [comment]
感谢百忙之中回复消息，就是不好意思，因为这个比赛我当时没有参加，没有报名没法下载呢，不知道能麻烦放在网盘里给个链接分享一下数据么😌
十分感谢学习链接的分享🙏🙏🙏
王海涛 <notifications@github.com> 于2018年12月5日周三 下午7:56写道：

**Comment by binaryOmaire** [comment]
https://jdder.jd.com/index/jddDetail?matchId=0890e7edc3c840ea9351e9d736da1e16
链接不能下载数据啦，能否分享一下数据吗？
